package com.example.demo.controller;

import com.example.demo.dominio.Endereco;
import com.example.demo.repositorio.EnderecoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping("/enderecos") // This means URL's start with /demo (after Application path)
public class EnderecoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EnderecoRepository enderecoRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestBody Endereco e) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        enderecoRepository.save(e);
        return "Saved";
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<Endereco> getAllEnderecos() {
        // This returns a JSON or XML with the users
        return enderecoRepository.findAll();
    }
}
