-- MySQL Script generated by MySQL Workbench
-- Tue Oct 12 22:48:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- ---UPDATE `sportybd`.`atleta`

--------------------------------------------------
-- Schema sportybd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportybd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportybd` DEFAULT CHARACTER SET utf8 ;
USE `sportybd` ;

-- -----------------------------------------------------
-- Table `sportybd`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportybd`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` CHAR(8) NULL,
  `logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportybd`.`Quadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportybd`.`Quadra` (
  `id_quadra` INT NOT NULL AUTO_INCREMENT,
  `nome_quadra` VARCHAR(45) NULL,
  `desc_quadra` VARCHAR(300) NULL,
  `limite_pessoas` INT NULL,
  `classificacao_quadra` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`id_quadra`),
  INDEX `fk_Quadra_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Quadra_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `sportybd`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportybd`.`Atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportybd`.`Atleta` (
  `id_atleta` INT NOT NULL AUTO_INCREMENT,
  `cpf` CHAR(11) NULL,
  `nome_atleta` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `data_nasc` DATE NULL,
  `Endereco_idEndereco` INT NOT NULL,
  INDEX `fk_Atleta_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  PRIMARY KEY (`id_atleta`),
  CONSTRAINT `fk_Atleta_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `sportybd`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportybd`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportybd`.`Reservas` (
  `hora_partida` DATETIME NOT NULL,
  `Quadra` INT NOT NULL,
  `responsavel` INT NOT NULL,
  `qtd_atletas` VARCHAR(45) NULL,
  `valor_reserva` VARCHAR(45) NULL,
  PRIMARY KEY (`hora_partida`),
  INDEX `fk_Atleta_has_Quadra_Quadra1_idx` (`Quadra` ASC) VISIBLE,
  INDEX `fk_Reservas_Atleta1_idx` (`responsavel` ASC) VISIBLE,
  CONSTRAINT `fk_Atleta_has_Quadra_Quadra1`
    FOREIGN KEY (`Quadra`)
    REFERENCES `sportybd`.`Quadra` (`id_quadra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Atleta1`
    FOREIGN KEY (`responsavel`)
    REFERENCES `sportybd`.`Atleta` (`id_atleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
atleta